project:
  type: website

website:
  title: "fonogram"
  site-url: www.fonogram.nu
  navbar:
    right:
      - blog.qmd
      
format:
  html:
    theme: solar
    css: styles.css

editor: visual

execute:
  freeze: auto

