project:
  type: website

website:
  title: "fonogram"
  site-url: https://ubuuph5y.github.io.
  navbar:
    right:
      - text: innehåll
        href: blog.qmd
      
format:
  html:
    theme: solar
    

editor: visual

execute:
  freeze: auto


