---
title: "Post-punken frodas"
date: 02-22-22
---

## Två post-punkband som gör det värt att minnas åttiotalet igen

Vi måste prata post-punk. Det är en genre som tyst har blommat i några år, och som tittar tillbaka på åtttiotalets första hälft. Post-punken är tillräckligt gammal för att generation Z ska upptäcka den på nytt och tillföra en egen tolkning. Nedan är två bra exempel.

### Beverly Kills -- ett eko från åttiotalet

{{< figure src="https://i.scdn.co/image/ab67616d0000b27391e7e7ce801ef47489f8bb54" title="Elegance in a State of Crisis" class="left" width="300" height="300" >}} Först ut är Beverly Kills och deras EP Elegance in a State of Crisis \[Vinyl\]. Musiken för mig tillbaka till klassiskt brittiska musikprogram som Channel 4:s The Tube. Det svänger rejält om musiken och jag ser publikhavet böljar framför mig. Bilder i produktionen blandas med grodperspektiv med rök och neonljus och svepande bilder över hoppande publik med scen och artister i förgrunden.

I produktionen lagras synt- och gitarrslingor ovanpå varandra tillsammans med en mycket skicklig batterist, och basist som levererar sirliga basgångar. Ljudbilden är en blandning av en lagom dos ståltråd i gitarrslingor och värme i mellanregistret i främst i basen. syntslingor som levererar antydan till ödesmättnad men innan saker och ting barkat åt skogen. Partyt finns fortfarande kvar och aptit på livet. Kort sagt det svänger rejält. EP:n är riktigt bra och mitt förbehåll är att knappt nitton minuter är för kort eftersom jag vill ha mer.

### Isolated Youth skildrar steget efter ungdomens partyknarkande

{{< figure src="https://i.scdn.co/image/ab67616d0000b273f52ec862c453d2e56c662058" title="Iris" class="left" width="300" height="300" >}}Isolated Youth EP Iris \[Vinyl\]. I jämförelse med Beverly Kills har avgrunden öppnat sig och livet är inte ett rosa partyknarkande längre. Det är det äldre syskonet vars sviter av den sorglösa ungdomens leverne hann ikapp före adolescensen. Joy Division-riff och sången är spröd falsett. Känslorna ligger utanpå kroppen. Dock famlar tematiken i texterna något. Jag egentligen är mer av en helhetslyssnare - att magkänslan och produktion och ljudbild är viktigare än texten.

### Låten 1984 förpliktigar i ett ungt band

Det finns dock ett men kring texterna. Att ha med en låttitel som "1984" och dessutom vara ett post-punkband förpliktigar en del. Framförallt när vi vet att världen på att gå åt skogen 1983/84. (Gör en googlesökning på Able Archer). Dock är jag villig att förlåta formen före innehållet i texterna.

Isolated Youth sjunger: \*Karate kicks In bookshop queues/ Crying children On pay-per-view /The working class is undead /And we're the isolated youth.\* Uttrycket blir anakronistiskt eftersom arbetarklassen var inte odöda zombier 1983. Välfärdsstaten var på väg att rullas ut för fullt i Sverige med en barnomsorg som nådde full utbyggnad. Pay-per-view fanns inte 1984. Dock slog MTV igenom stort kabel-tv i USA och sedermera i Europa när kabel-tv lanserades.

Isolated Youth fortsätter att sjunga att "Oh 1983 It missed me" och jag missar dem med. Textförfattandet är mest ett dadaistiskt formexperiment. Ord staplas på varandra utan mening eller innehåll. Vilket är synd eftersom känsla, ljudbild och produktion är så väldigt bra.
