---
title: "boygenius"
format: html
---

## the record -- ett urklipp mellan att leva som millenial och z

Skivan är fylld av harmonier mellan tre soloartister. Deras röster och musikaliska uttryck ständigt korspollineras, och medlemmarnas röstlägen glider in och ut från varandra. Phoebe Bridgers vurmar för Elliot Smith och Lucy Dacus är som bäst genom att vara sig själv. Den konstnärliga ambitionerna lever högt men jag kommer att återkomma till produktionen av den konstnärliga presentationen. Gruppens medlemmar har ett uttalat syfte att det ska vara roligt att spela in musik utan inbördes konkurrens. Julien Baker, Phoebe Bridgers och Lucy Dacus är etablerade soloartister och de är födda i mitten på 90-talet.

### En bloggande rörgubbe ledde mig till Lucy Dacus

Ett inlägg som har en rubrik och två meningar ledde mig till Lucy Dacus varav den första meningen lyder: *Just heard Lucy Dacus on CBS TV singing selections from her sophomore album and it was great.* Inlägget kommer från en gubbe som mest bloggar om rörförstärkare och högtalare som en vanlig dödlig löntagare bara kan drömma om. Rörgubben skriver väldigt mycket om klassisk musik, och jag har själv plockat upp några guldkorn på rekommendation från bloggen. Döm av förvåning när jag läste om Lucy Dacus skiva *Historian*.

### Historian är en ulv i fårakläder

Jag lyssnade på *Historian* och tyckte den var värdig ett inköp på vinyl. Den är trevlig. Lucy Dacus har en uttrycksfull röst men kanske 3 av 5. Ett gediget hantverk, men ja en andra skiva som kanske inte träffat rätt än efter den lovvärda debuten. Jag hade fel. Det finns så många lager i den skivan som smyger sig på efter varje lyssning. Lagren har en tendens att skifta sedan den senaste lyssningen. *Historian* är en skiva som jag ofta återvänder till.

### Boygenius är en supergrupp som sätter ribban högt

Medlemmernas solokarriärer är fyllda av politisk medventenhet och aktivism. Det märks att medlemmarna har tagit fasta på att boygenius ska vara en prestigelös kreativ miljö. The record är en smältdegel med tre soloartister, och formen låter gjuta en skiva med musikalisk spänst. Utan att det sakens skull smälta ned personliga uttryck. Sammantaget är skivan en helhet som tillåter individuella exkursioner i musiklandskapet.

### Låtar som gör ett avtryck på trumhinnan

*Emily I'm sorry* doftar Elliot Smith och stämsången i bakgrunden som gör den till något eget. Att vara vilsen är inte något som enbart förknippas med unga personer (även fast adolescens handlar om att hitta sig själv och bli vuxen). Strofen *I am 27 and I don't know who I am, but I know what I want* gör låten till något allmänmänskligt och något som inte enbart är förknippat med ungdomen. *True Blue* är en låter när Lucy Dacus är som allra bäst. Det är svårt att sätta fingret på vad som gör den bra. Det är något med hur Lucy Dacus fraserar och använder små röstlägen för att förmedla en känsla.

### Produktionen är det nya normala efter loudness wars i mitten på nittiotalet

Nu kommer vi till den stora invändningen mot skivan. Mastringen skulle må bra av att andas och lättas upp för att släppa in mer dynamik i produktionen. Vilket ställer frågan om hur ofta jag kommer att lyssna på *the record* hemma. Jag har lyssnat på skivan genom hörlurar och med Spotify (spotify inställt på högsta ljudkvalitet) och där är ljudet bra. Men det låter hörlurar och jag föredrar att lyssna i tvåkanaler och stereo. Mastringen har en ambition att erbjuda lyssning i två kanaler och det finns fina lager och djup.

### Ljudbilden på the record saknar djup och bredd

Ljudbilden när du lyssnar med hjälp av högtalare via två kanaler är tyvärr koncentrerad till mitten, och bristen på dynamik gör att den känns forcerad. En slagning i *Dynamic Range DB* ger en röd åtta vilket indikerar att mastringen kan ligga på gränsen att begränsa dynamiken i produktionen. Det bekräftar lyssningsintrycket från högtalare. En skiva som jag har hemma med amerikanska kvinnor som spelar indierock är Laura Gibson *Empire builder* . *Empire builder* andas betydligt mer och låter mycket mer avslappnat framförall erbjuder den lyssning via något annat än din telefon med hjälp av sladdlösa vita ploppar. Sammantaget drar mastringen ned det konstnärliga intrycket från en annars mycket bra skiva.
